## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
#Wed Jun 04 21:50:44 IST 2025
android.defaults.buildfeatures.resvalues=true
android.dependency.useConstraints=true
android.enableJetifier=false
android.lifecycleProcessor.incremental=true
android.nonFinalResIds=true
android.nonTransitiveRClass=true
android.onlyEnableUnitTestForTheTestedBuildType=false
android.r8.optimizedResourceShrinking=false
android.r8.strictFullModeForKeepRules=false
android.uniquePackageNames=false
android.useAndroidX=true
android.usesSdkInManifest.disallowed=false
kotlin.code.style=official
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx3072M -XX\:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx3072M" -XX\:+UseParallelGC
org.gradle.parallel=true
systemProp.sonar.host.url=http\://localhost\:9000
systemProp.sonar.projectKey=SCUS
systemProp.sonar.token=sqp_5a48a8580fa6434b5d0fdc3d0891e298cc24c119
android.dependency.excludeLibraryComponentsFromConstraints=false