
android.enableJetifier=false
android.useAndroidX=true
android.lifecycleProcessor.incremental=true
android.nonFinalResIds=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx3g" -XX\:+UseParallelGC
org.gradle.parallel=true
systemProp.sonar.host.url=http\://localhost\:9000
systemProp.sonar.projectKey=SCUS
systemProp.sonar.token=sqp_5a48a8580fa6434b5d0fdc3d0891e298cc24c119