android.builtInKotlin=true
android.dependency.useConstraints=true
android.enableAppCompileTimeRClass=true
android.enableJetifier=false
android.excludeLibraryComponentsFromConstraints=true
android.lifecycleProcessor.incremental=true
android.newDsl=true
android.nonFinalResIds=true
android.nonTransitiveRClass=true
android.onlyEnableUnitTestForTheTestedBuildType=false
android.r8.optimizedResourceShrinking=true
android.r8.strictFullModeForKeepRules=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=true
android.uniquePackageNames=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.incremental.native=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx3072M -XX\:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx3072M" -XX\:+UseParallelGC
org.gradle.parallel=true
systemProp.sonar.host.url=http\://localhost\:9000
systemProp.sonar.projectKey=SCUS
systemProp.sonar.token=sqp_5a48a8580fa6434b5d0fdc3d0891e298cc24c119
