[versions]

# App Name
debugAppName = "SCUS"
betaAppName = "SCUS Beta"
releaseAppName = "SCUS"

# Build Variables
apkName = "SCUS"

# Package Names
nameSpace = "io.github.raghavsatyadev.scus"
appIdDev = "io.github.raghavsatyadev.scus"
appIdProd = "io.github.raghavsatyadev.scus"
supportId = "io.github.raghavsatyadev.support"
sharedAndroidId = "io.github.raghavsatyadev.android.library"

# SDK Versions
targetSdk = "36"
targetSdkPreview = "Baklava"
minSdk = "26"
compileSdk = "36"
compileSdkPreview = "Baklava"

buildTools = "36.1.0"

# App Version Codes
versionCode = "4"
versionName = "1.0.0"

# Plugin Versions
agp = "9.2.0-alpha06"
kotlin = "2.3.20"
kotlinx-datetime = "0.7.1"
ksp = "2.3.6"
google-plugin = "4.4.4"

# Library Versions
activity = "1.13.0"
androidx-core = "1.18.0"
androidx-junit = "1.3.0"
androidx-test = "1.7.0"
coil = "3.4.0"
collection = "1.6.0"
compose-constraint = "1.1.1"
compose-constraint-mp = "0.7.0"
compose-material3 = "1.5.0-alpha16"
compose-material3-mp = "1.10.0-alpha05"
compose-multiplatform = "1.11.0-beta01"
compose-ui = "1.11.0-beta02"
concurrent-futures = "1.3.0"
coroutines = "1.10.2"
credentials = "1.6.0-rc02"
datastore = "1.3.0-alpha07"
desugar-jdk-libs = "2.1.5"
firebase-analytics = "23.2.0"
firebase-appcheck = "19.0.2"
firebase-auth = "24.0.1"
firebase-crashlytics = "20.0.4"
firebase-firestore = "26.1.2"
firebase-crashlytics-gradle = "3.0.6"
firebase-messaging = "25.0.1"
gitlive-firebase = "2.4.0"
google-id = "1.2.0"
integrity = "1.6.0"
koin = "4.2.0"
kotzilla = "2.1.1"
junit = "4.13.2"
lifecycle = "2.11.0-alpha03"
lifecycle-mp = "2.10.0"
navigation3 = "1.1.0-rc01"
navigation3-mp = "1.1.0-beta01"
navigation3-adaptive = "1.3.0-alpha06"
play-services-ads = "25.1.0"
play-services-auth = "21.5.1"
room = "2.8.4"
room-sqlite = "2.6.2"
serialization = "1.10.0"
sonarqube = "7.2.3.7755"
splashscreen = "1.2.0"
stability-analyzer = "0.7.1"
startup = "1.2.0"
work-manager = "2.11.2"
logback = "1.5.32"

[libraries]
# Classpaths
firebase-gradle-plugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# Android
androidx-collection = { module = "androidx.collection:collection-ktx", version.ref = "collection" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrent-futures" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-play-credentials = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }

#Compose
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-constraint = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraint" }

compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
compose-ui-font = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "compose-ui" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
compose-ui-animation = { module = "androidx.compose.animation:animation", version.ref = "compose-ui" }

# Compose Multiplatform
compose-ui-mp = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-foundation-mp = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-material3-mp = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3-mp" }
compose-components-resources-mp = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-ui-tooling-preview-mp = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-runtime-mp = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-constraint-mp = { module = "tech.annexflow.compose:constraintlayout-compose-multiplatform", version.ref = "compose-constraint-mp" }

#Kotlin
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

#Lifecycle
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycle" }

# Lifecycle Multiplatform
lifecycle-viewmodel-compose-mp = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-mp" }
lifecycle-runtime-compose-mp = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-mp" }
lifecycle-viewmodel-navigation3-mp = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycle-mp" }

#Navigation
navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
navigation3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "navigation3-adaptive" }
navigation3-ui-mp = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3-mp" }

# Koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }

# Koin Multiplatform
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose-mp = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel-mp = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

kotzilla-sdk-compose = { group = "io.kotzilla", name = "kotzilla-sdk-compose", version.ref = "kotzilla" }

#Firebase
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-appcheck-debug = { module = "com.google.firebase:firebase-appcheck-debug", version.ref = "firebase-appcheck" }
firebase-appcheck-playintegrity = { module = "com.google.firebase:firebase-appcheck-playintegrity", version.ref = "firebase-appcheck" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase-auth" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebase-firestore" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-messaging" }

# Firebase Multiplatform (GitLiveApp)
gitlive-firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "gitlive-firebase" }
gitlive-firebase-firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "gitlive-firebase" }
gitlive-firebase-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "gitlive-firebase" }

#Google
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "play-services-ads" }
google-id = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "google-id" }
play-integrity = { module = "com.google.android.play:integrity", version.ref = "integrity" }

#Room
room = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

# Room Multiplatform
room-sqlite-bundled-mp = { module = "androidx.sqlite:sqlite-bundled", version.ref = "room-sqlite" }

#WorkManager
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work-manager" }

#Coil
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }

# Coil Multiplatform
coil-compose-mp = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor-mp = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

#Support
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }

#Tests
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-core = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }

google-plugin = { id = "com.google.gms.google-services", version.ref = "google-plugin" }

kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
room = { id = "androidx.room", version.ref = "room" }
stability-analyzer = { id = "com.github.skydoves.compose.stability.analyzer", version.ref = "stability-analyzer" }
crashlytics = { id = "com.google.firebase.crashlytics" }

kotzilla = { id = "io.kotzilla.kotzilla-plugin", version.ref = "kotzilla" }

[bundles]
kotlin = [
    "kotlin-stdlib-jdk8",
    "kotlinx-coroutines-android",
    "kotlinx-coroutines-core",
    "kotlinx-serialization-json",
]
androidx = [
    "androidx-collection",
    "androidx-concurrent-futures",
    "androidx-core",
    "androidx-credentials",
    "androidx-datastore-preferences",
    "androidx-play-credentials",
    "androidx-splashscreen",
    "androidx-startup",
]
coil = [
    "coil",
]
coil-mp = [
    "coil-compose-mp",
    "coil-network-ktor-mp",
]
compose = [
    "compose-activity",
    "compose-constraint",
    "compose-material3",
    "compose-ui-font",
    "compose-ui-preview",
    "compose-ui-animation",
]
android-mp = [
    "androidx-splashscreen",
    "compose-ui-preview",
    "compose-activity",
    "koin-core",
    "koin-android",
    "koin-androidx-compose",
    "koin-compose-mp",
    "koin-compose-viewmodel-mp",
    "koin-androidx-workmanager",
]
compose-mp = [
    "compose-ui-mp",
    "compose-ui-tooling-preview-mp",
    "compose-foundation-mp",
    "compose-material3-mp",
    "compose-components-resources-mp",
    "compose-runtime-mp",
    "compose-constraint-mp",
]
firebase = [
    "firebase-analytics",
    "firebase-appcheck-debug",
    "firebase-appcheck-playintegrity",
    "firebase-auth",
    "firebase-crashlytics",
    "firebase-firestore",
    "firebase-messaging",
]
firebase-mp = [
    "gitlive-firebase-auth",
    "gitlive-firebase-firestore",
    "gitlive-firebase-crashlytics",
]
google = [
    "google-id",
    "play-services-ads",
    "play-services-auth",
    "play-integrity",
]
koin = [
    "koin-android",
    "koin-androidx-compose",
    "koin-androidx-workmanager",
]
koin-mp = [
    "koin-core",
    "koin-compose-mp",
    "koin-compose-viewmodel-mp",
]
lifecycle = [
    "lifecycle-common-java8",
    "lifecycle-runtime",
    "lifecycle-viewmodel",
    "lifecycle-viewmodel-compose",
    "lifecycle-viewmodel-navigation3",
]
lifecycle-mp = [
    "lifecycle-viewmodel-compose-mp",
    "lifecycle-runtime-compose-mp",
    "lifecycle-viewmodel-navigation3-mp",
]
navigation = [
    "navigation3-runtime",
    "navigation3-ui",
    "navigation3-adaptive",
]
navigation-mp = [
    "navigation3-ui-mp",
]
other = [
    "androidx-work-runtime",
]
room = [
    "room",
    "room-runtime",
]
room-mp = [
    "room-runtime",
    "room-sqlite-bundled-mp",
]
ksp = [
    "room-compiler",
]
test = [
    "androidx-junit",
    "androidx-room-testing",
    "androidx-rules",
    "androidx-runner",
    "androidx-test-core",
    "junit",
    "koin-test",
    "koin-test-junit4",
]
androidTest = [
    "androidx-junit",
    "androidx-room-testing",
    "androidx-rules",
    "androidx-runner",
    "androidx-test-core",
    "compose-ui-test-junit4",
]
debug = [
    "compose-ui-test-manifest",
    "compose-ui-tooling",
]

update-libs = [
    "firebase-gradle-plugin",
    "kotlin-gradle-plugin",
    "androidx-collection",
    "androidx-concurrent-futures",
    "androidx-core",
    "androidx-credentials",
    "androidx-datastore-preferences",
    "androidx-play-credentials",
    "androidx-splashscreen",
    "androidx-startup",
    "compose-material3",
    "compose-activity",
    "compose-constraint",
    "compose-ui-preview",
    "compose-ui-font",
    "compose-ui-test-junit4",
    "compose-ui-test-manifest",
    "compose-ui-tooling",
    "compose-ui-animation",
    "compose-ui-mp",
    "compose-foundation-mp",
    "compose-material3-mp",
    "compose-components-resources-mp",
    "compose-ui-tooling-preview-mp",
    "compose-runtime-mp",
    "compose-constraint-mp",
    "kotlin-stdlib-jdk8",
    "kotlinx-datetime",
    "kotlinx-coroutines-android",
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-swing",
    "kotlinx-serialization-json",
    "logback-classic",
    "lifecycle-common-java8",
    "lifecycle-viewmodel",
    "lifecycle-runtime",
    "lifecycle-viewmodel-compose",
    "lifecycle-viewmodel-navigation3",
    "lifecycle-viewmodel-compose-mp",
    "lifecycle-runtime-compose-mp",
    "lifecycle-viewmodel-navigation3-mp",
    "navigation3-runtime",
    "navigation3-ui",
    "navigation3-adaptive",
    "navigation3-ui-mp",
    "koin-android",
    "koin-androidx-compose",
    "koin-androidx-workmanager",
    "koin-test",
    "koin-test-junit4",
    "koin-core",
    "koin-compose-mp",
    "koin-compose-viewmodel-mp",
    "kotzilla-sdk-compose",
    "firebase-analytics",
    "firebase-appcheck-debug",
    "firebase-appcheck-playintegrity",
    "firebase-auth",
    "firebase-crashlytics",
    "firebase-firestore",
    "firebase-messaging",
    "gitlive-firebase-auth",
    "gitlive-firebase-firestore",
    "gitlive-firebase-crashlytics",
    "play-services-auth",
    "play-services-ads",
    "google-id",
    "play-integrity",
    "room",
    "room-compiler",
    "room-runtime",
    "room-sqlite-bundled-mp",
    "androidx-work-runtime",
    "coil",
    "coil-compose-mp",
    "coil-network-ktor-mp",
    "desugar_jdk_libs",
    "androidx-junit",
    "androidx-room-testing",
    "androidx-rules",
    "androidx-runner",
    "androidx-test-core",
    "junit",
]